/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ulbra.view;

import br.ulbra.controller.ChamadoController;
import br.ulbra.dao.EquipamentoDAOImpl;
import br.ulbra.dao.UsuarioDAOImpl;
import br.ulbra.model.Chamado;
import br.ulbra.model.Equipamento;
import br.ulbra.model.Usuario;
import br.ulbra.utils.Sessao;
import java.sql.Timestamp;

import java.util.Date; // IMPORTANTE: tem que ser UTIL e não SQL
import java.text.SimpleDateFormat;

import java.util.List;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author qijef
 */
public class ChamadoView extends javax.swing.JFrame {

    /**
     * Creates new form ChamadoView
     */
    public ChamadoView() {
        initComponents();
        this.setLocationRelativeTo(null);
        listarTabela();
        carregarCombos();
// NOVIDADE: Seleciona o usuário da sessão no ComboBox
        if (Sessao.getUsuario() != null) {
            configurarUsuarioLogado();
        }
    }

    private void configurarUsuarioLogado() {
        Usuario logado = Sessao.getUsuario();

        if (logado == null) {
            return; // Segurança caso não haja sessão
        }
        // Percorre o combo
        for (int i = 0; i < cbSolicitante.getItemCount(); i++) {
            // O truque está aqui: Pegamos como Object primeiro
            Object item = cbSolicitante.getItemAt(i);

            // Verificamos se o item é do tipo Usuario antes de converter
            if (item instanceof Usuario) {
                Usuario u = (Usuario) item;

                if (u.getId() == logado.getId()) {
                    cbSolicitante.setSelectedIndex(i);
                    break;
                }
            }

            // Opcional: Trava o combo para o usuário não mudar o solicitante
            cbSolicitante.setEnabled(false);
        }
        // Opcional: desabilita o combo para o usuário não abrir chamado no nome de outro
        cbSolicitante.setEnabled(false);
    }
    ChamadoController controller = new ChamadoController();

    private void carregarCombos() {
        // Carregando Usuários
        List<Usuario> usuarios = new UsuarioDAOImpl().listarTodos();
        DefaultComboBoxModel modelUser = new DefaultComboBoxModel();
        for (Usuario u : usuarios) {
            modelUser.addElement(u); // Adiciona o objeto inteiro
        }
        cbSolicitante.setModel(modelUser);

        // Carregando Equipamentos
        List<Equipamento> equipamentos = new EquipamentoDAOImpl().listarTodos();
        DefaultComboBoxModel modelEqui = new DefaultComboBoxModel();
        for (Equipamento e : equipamentos) {
            modelEqui.addElement(e); // Adiciona o objeto inteiro
        }
        cbEquipamento.setModel(modelEqui);
    }

    public void listarTabela() {
        DefaultTableModel model = (DefaultTableModel) tbChamado.getModel();
        model.setRowCount(0);

        // Pegamos o usuário da sessão
        Usuario logado = Sessao.getUsuario();
        JOptionPane.showMessageDialog(this, logado.getId());
        // Chamamos o novo método do DAO passando o ID do logado
        // Nota: Certifique-se que o seu Controller tenha o método correspondente
        List<Chamado> chamados = controller.listarPorUsuario(logado.getId());

        for (Chamado c : chamados) {
            model.addRow(new Object[]{
                c.getId(),
                c.getUsuario().getNome(),
                c.getEquipamento().getTag_patrimonio(),
                c.getEquipamento().getSala(),
                c.getProblemaRelatado(),
                c.getDiagnosticoTecnico(),
                c.getPrioridade(),
                c.getStatus(),
                c.getDataAbertura()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtProblema = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtDiagnostico = new javax.swing.JTextArea();
        jLabel7 = new javax.swing.JLabel();
        cbPrioridade = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        chStatus = new javax.swing.JCheckBox();
        jLabel9 = new javax.swing.JLabel();
        btnSalvar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbChamado = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        cbSolicitante = new javax.swing.JComboBox<>();
        cbEquipamento = new javax.swing.JComboBox<>();
        txtData = new datechooser.beans.DateChooserCombo();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        jLabel1.setText("ABERTURA DE CHAMADO");

        jLabel2.setText("SOLICITANTE");

        jLabel4.setText("EQUIPAMENTO");

        jLabel5.setText("RELATO DO PROBLEMA");

        txtProblema.setColumns(20);
        txtProblema.setRows(5);
        jScrollPane2.setViewportView(txtProblema);

        jLabel6.setText("DIAGNÓSTICO TÉCNICO");

        txtDiagnostico.setColumns(20);
        txtDiagnostico.setRows(5);
        jScrollPane3.setViewportView(txtDiagnostico);

        jLabel7.setText("PRIORIDADE");

        cbPrioridade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Baixa", "Média", "Alta" }));

        jLabel8.setText("STATUS");

        chStatus.setSelected(true);
        chStatus.setText("ATIVO");

        jLabel9.setText("DATA ABERTURA");

        btnSalvar.setText("SALVAR");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        tbChamado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Solicitante", "Equipamento", "Sala", "Problema", "Diagnostico", "Prioridade", "Status", "Data Abertura"
            }
        ));
        tbChamado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbChamadoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbChamado);

        jLabel10.setText("LISTAGEM DE CHAMADOS");

        jButton2.setText("EDITAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("EXCLUIR");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel11.setText("ID");

        txtId.setEditable(false);

        jButton4.setText("LISTAR");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton1.setText("LIMPAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cbSolicitante.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbEquipamento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(chStatus))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnSalvar))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(83, 83, 83)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(209, 209, 209))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(312, 312, 312)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(jLabel1))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cbSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(cbEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(59, 59, 59)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6))))))
                        .addGap(0, 50, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel11)
                    .addComponent(cbSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbEquipamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(chStatus))
                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cbPrioridade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(txtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel10)
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(96, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        try {
            // 1. VALIDAÇÃO DE SELEÇÃO (Combos)
            if (cbSolicitante.getSelectedItem() == null || cbEquipamento.getSelectedItem() == null) {
                JOptionPane.showMessageDialog(null, "Por favor, selecione um solicitante e um equipamento!");
                return;
            }

            // 2. CAPTURA DOS OBJETOS (Recuperando os IDs reais do banco)
            Object objUser = cbSolicitante.getSelectedItem();
            Object objEqui = cbEquipamento.getSelectedItem();

            // Verificação de segurança (Garante que o cast não vai falhar)
            if (!(objUser instanceof Usuario) || !(objEqui instanceof Equipamento)) {
                JOptionPane.showMessageDialog(null, "Erro: Os itens selecionados não são objetos válidos.");
                return;
            }

            Usuario user = (Usuario) objUser;
            Equipamento equip = (Equipamento) objEqui;

            // 3. CAPTURA DOS CAMPOS DE TEXTO E COMPONENTES
            int idUser = user.getId(); // Use getIdUsuario() se for o nome no seu Model
            int idEqui = equip.getId_equipamento();

            String problema = txtProblema.getText().trim();
            String diagnostico = txtDiagnostico.getText().trim();
            String prioridade = cbPrioridade.getSelectedItem().toString();
            String status = chStatus.isSelected() ? "Ativo" : "Não Ativo";
//            String data = txtData.getText().trim();
// PEGA A DATA DO COMPONENTE E FORMATA COMO STRING
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

            // Se estiver usando o JDateChooser (biblioteca externa):
            // String dataString = sdf.format(jdDataAbertura.getDate());
            // Se estiver usando um JFormattedTextField com máscara:
            String dataString = txtData.getText();

            String mensagem = controller.cadastrar(
                    idUser,
                    idEqui,
                    problema,
                    diagnostico,
                    prioridade,
                    status,
                    dataString
            );

            // 6. FEEDBACK E ATUALIZAÇÃO DA TELA
            JOptionPane.showMessageDialog(null, mensagem);
            limpar(); // Limpa os campos após salvar
            listarTabela(); // Recarrega a JTable com o novo chamado

        } catch (IllegalArgumentException e) {
            // Erro específico de formato de data no Timestamp.valueOf
            JOptionPane.showMessageDialog(null, "Erro no formato da data! Use: yyyy-mm-dd hh:mm:ss");
        } catch (Exception e) {
            // Qualquer outro erro (Banco, NullPointer, etc)
            e.printStackTrace();
            JOptionPane.showMessageDialog(null, "Erro ao salvar: " + e.getMessage());
        }


    }//GEN-LAST:event_btnSalvarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int id = Integer.parseInt(txtId.getText());
        if (chStatus.isSelected()) {
            chStatus.setSelected(true);
        } else {
            chStatus.setSelected(false);
        }

        String status = "Não Ativo";
        if (chStatus.isSelected()) {
            status = "Ativo";
        }
        String prioridade = cbPrioridade.getSelectedItem().toString();

        /*  String msg = controller.atualizar(
                id,
                txtSolicitante.getText(),
                txtSala.getText(),
                txtEquipamento.getText(),
                txtProblema.getText(),
                txtDiagnostico.getText(),
                prioridade,
                status,
                txtData.getText()
        );

        JOptionPane.showMessageDialog(null, msg);*/
        listarTabela();

    }//GEN-LAST:event_jButton2ActionPerformed

    private void tbChamadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbChamadoMouseClicked
        int linha = tbChamado.getSelectedRow();

// Campos de texto (você já fez estes)
/*
        txtId.setText(tbChamado.getValueAt(linha, 0).toString());
        txtSolicitante.setText(tbChamado.getValueAt(linha, 1).toString());
        txtSala.setText(tbChamado.getValueAt(linha, 2).toString());
        txtEquipamento.setText(tbChamado.getValueAt(linha, 3).toString());
        txtProblema.setText(tbChamado.getValueAt(linha, 4).toString());
        txtDiagnostico.setText(tbChamado.getValueAt(linha, 5).toString());

// --- ADICIONE ESTAS LINHAS AQUI ---
// 1. Trata o JComboBox (Prioridade - Coluna 6)
        String prioridade = tbChamado.getValueAt(linha, 6).toString();
        cbPrioridade.setSelectedItem(prioridade);

// 2. Trata o JCheckBox (Status - Coluna 7)
        String status = tbChamado.getValueAt(linha, 7).toString();
        chStatus.setSelected(status.equalsIgnoreCase("Ativo"));

// --- FIM DA ADIÇÃO ---
        txtData.setText(tbChamado.getValueAt(linha, 8).toString());
         */
    }//GEN-LAST:event_tbChamadoMouseClicked
    public void limpar() {
        /*      txtSolicitante.setText(null);*/
        txtDiagnostico.setText(null);
        txtData.setText(null);
        /*txtEquipamento.setText(null);*/
        txtId.setText(null);
        txtProblema.setText(null);

        chStatus.setSelected(true);
        cbPrioridade.setSelectedIndex(0);
    }
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        listarTabela();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpar();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int confirm = JOptionPane.showConfirmDialog(null, "Deseja excluir o problema " + txtProblema.getText() + " ? ", "Exclusão", JOptionPane.YES_NO_OPTION);
        int id = Integer.parseInt(txtId.getText());
        if (confirm == JOptionPane.YES_OPTION) {
            String msg = controller.deletar(id);
            JOptionPane.showMessageDialog(null, msg);
            listarTabela();
        } else {
            JOptionPane.showMessageDialog(null, "Operação cancelada!");
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChamadoView.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChamadoView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSalvar;
    private javax.swing.JComboBox<String> cbEquipamento;
    private javax.swing.JComboBox<String> cbPrioridade;
    private javax.swing.JComboBox<String> cbSolicitante;
    private javax.swing.JCheckBox chStatus;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable tbChamado;
    private datechooser.beans.DateChooserCombo txtData;
    private javax.swing.JTextArea txtDiagnostico;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextArea txtProblema;
    // End of variables declaration//GEN-END:variables
}
